language: swift
osx_image: xcode10.1
git:
  depth: false # To enable build numbering from an accurate commit count
cache:
  bundler: true
  cocoapods: true
  directories:
    - $HOME/Library/Caches/Homebrew/
    - /usr/local/lib/mint/
install:
  - bundle install
  - brew install mint
  - pod repo update
before_script:
  - bundle exec fastlane preprocess
script:
  - bundle exec fastlane ci
deploy:
  skip_cleanup: true
  provider: script
  script:
    - bundle exec fastlane upload_build
  on:
    branch: master
after_deploy:
  - bundle exec fastlane tag_build